version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
            name: chmod permissions
            command: chmod +x ./gradlew
#      - run:
#            name: 'Download Dependencies'
#            command: './gradlew androidDependencies'

        - run:
            name: 'Socket App'
            command: './gradlew app:assembleDebug'
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      #- run: gradle test



