# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :deploy do
    # app should be autocreated if not found
    appcenter_upload(
      api_token: "57c5d832209fe8ee9808333ba71fd86e4cf8f6b4",
      owner_name: "guido.rubin-pager.com",
      app_name: "CircleApp",
      apk: "app/build/outputs/apk/debug/app-debug.apk"
    )
  end

  lane :test do
    android_get_version_name(
      gradle_file: "app/build.gradle" # optional
    )

    android_set_version_name(
      version_name: "1.23.4",
      gradle_file: "app/build.gradle" # optional
    )

    android_get_version_code(
      gradle_file: "app/build.gradle" # optional
    )

    android_set_version_code(
      version_code: 17, # optional, if not specified, Version Code will be incremented
      gradle_file: "app/build.gradle" # optional
    )
  end

end
