# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :deploy do
    # app should be autocreated if not found
    appcenter_upload(
      api_token: ${appcenter_token},
      owner_name: guido.rubin-pager.com,
      app_name: CircleCi,
      apk: "./fastlane/app-release.apk"
    )
  end

end
